// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });

// @ts-nocheck
// Prisma 7-style config. Type-checking is disabled here on purpose so that
// `next build` doesn't fail when the installed prisma CLI version differs.
// The runtime config below is plain data and safe to keep untyped.
import "dotenv/config";

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
};